server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vendedor-service
          uri: https://vendedor-service.onrender.com
          predicates:
            - Path=/api/v1/vendedores/**
          filters:
            - RewritePath=/api/v1/vendedores/(?<segment>.*), /api/v1/vendedores/$\{segment}

        - id: administrador-service
          uri: https://administrador-service-aa6g.onrender.com
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - RewritePath=/api/v1/admin/(?<segment>.*), /api/v1/admin/$\{segment}

        - id: carrito-service
          uri: https://carrito-service-ma25.onrender.com
          predicates:
            - Path=/api/v1/carritos/**
          filters:
            - RewritePath=/api/v1/carritos/(?<segment>.*), /api/v1/carritos/$\{segment}

        - id: cliente-service
          uri: https://cliente-service-tj3v.onrender.com
          predicates:
            - Path=/api/v1/clientes/**
          filters:
            - RewritePath=/api/v1/clientes/(?<segment>.*), /api/v1/clientes/$\{segment}

        - id: delivery-service
          uri: https://delivery-service-9g24.onrender.com
          predicates:
            - Path=/api/v1/delivery/**
          filters:
            - RewritePath=/api/v1/delivery/(?<segment>.*), /api/v1/delivery/$\{segment}

        - id: catalogo-service
          uri: https://catalogo-service-msf3.onrender.com
          predicates:
            - Path=/api/productos/**
          filters:
            - RewritePath=/api/productos/(?<segment>.*), /api/productos/$\{segment}

        - id: reclamo-service
          uri: https://reclamo-service.onrender.com
          predicates:
            - Path=/api/reclamos/**
          filters:
            - RewritePath=/api/reclamos/(?<segment>.*), /api/reclamos/$\{segment}

        - id: pedido-service
          uri: https://pedido-service-3net.onrender.com
          predicates:
            - Path=/api/pedidos/**
          filters:
            - RewritePath=/api/pedidos/(?<segment>.*), /api/pedidos/$\{segment}

        - id: ventas-service
          uri: https://ventas-service-hv1x.onrender.com
          predicates:
            - Path=/api/ventas/**
          filters:
            - RewritePath=/api/ventas/(?<segment>.*), /api/ventas/$\{segment}

        - id: pago-service
          uri: https://pago-service-hbpk.onrender.com
          predicates:
            - Path=/api/pagos/**
          filters:
            - RewritePath=/api/pagos/(?<segment>.*), /api/pagos/$\{segment}