server.port=${PORT:10000}
spring.application.name=api-gateway

# Vendedores
spring.cloud.gateway.routes[0].id=vendedor-service
spring.cloud.gateway.routes[0].uri=https://vendedor-service.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/vendedores/**

# Administradores
spring.cloud.gateway.routes[1].id=administrador-service
spring.cloud.gateway.routes[1].uri=https://administrador-service-aa6g.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/admin/**

# Carritos
spring.cloud.gateway.routes[2].id=carrito-service
spring.cloud.gateway.routes[2].uri=https://carrito-service-ma25.onrender.com
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/carritos/**

# Clientes
spring.cloud.gateway.routes[3].id=cliente-service
spring.cloud.gateway.routes[3].uri=https://cliente-service-tj3v.onrender.com
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/clientes/**

# Delivery
spring.cloud.gateway.routes[4].id=delivery-service
spring.cloud.gateway.routes[4].uri=https://delivery-service-9g24.onrender.com
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/delivery/**

# Productos
spring.cloud.gateway.routes[5].id=catalogo-service
spring.cloud.gateway.routes[5].uri=https://catalogo-service-msf3.onrender.com
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/productos/**

# Reclamos
spring.cloud.gateway.routes[6].id=reclamo-service
spring.cloud.gateway.routes[6].uri=https://reclamo-service.onrender.com
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/reclamos/**

# Pedidos
spring.cloud.gateway.routes[7].id=pedido-service
spring.cloud.gateway.routes[7].uri=https://pedido-service-3net.onrender.com
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/pedidos/**

# Ventas
spring.cloud.gateway.routes[8].id=ventas-service
spring.cloud.gateway.routes[8].uri=https://ventas-service-hv1x.onrender.com
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/ventas/**

# Pagos
spring.cloud.gateway.routes[9].id=pago-service
spring.cloud.gateway.routes[9].uri=https://pago-service-hbpk.onrender.com
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/pagos/**